import { Link } from 'react-router-dom'
import type { Activity, ProgressData } from '../types/progress.types'
import { activityNames, studyDateLabel } from '../utils/progressDisplay'
export function ActivityList({ items, timeZone }: { items: Activity[]; timeZone: string }) {
  return <ol className="progress-activities">{items.map(item => <li key={item.id}>
    <div><span className="progress-kind">{activityNames[item.kind]}</span><strong>{item.label}</strong>
      <time dateTime={item.occurredAt}>{new Date(item.occurredAt).toLocaleString('vi-VN', { timeZone, dateStyle: 'short', timeStyle: 'short' })}</time>
      {(item.kind === 'QUIZ_SUBMITTED' || item.kind === 'FOUNDATION_SUBMITTED') && <small>{item.score}/100 điểm</small>}
      {item.kind === 'SKILL_PRACTICED' && <small>{item.score == null ? 'Luyện nói · tự đánh giá' : `${item.score}/100 điểm`}</small>}
      {item.kind === 'FLASHCARD_REVIEWED' && <small>{item.rating === 'REMEMBER' ? 'Tự đánh giá: Nhớ' : 'Tự đánh giá: Chưa nhớ'}</small>}
    </div><Link to={item.kind === 'FOUNDATION_SUBMITTED' ? '/foundations' : item.kind === 'SKILL_PRACTICED' ? '/skills/attempts/' + item.sourceId : item.kind === 'QUIZ_SUBMITTED' ? '/quizzes/attempts/' + item.sourceId : item.kind === 'LESSON_COMPLETED' && item.lessonId ? '/lessons/' + item.lessonId : '/flashcards/history'}>Xem lại →</Link>
  </li>)}</ol>
}
export function ProgressDashboard({ data }: { data: ProgressData }) {
  const { streak, totals, todayActivity } = data
  return <>
    <header className="study-heading"><p className="study-eyebrow">TỪNG NGÀY, TỪNG BƯỚC</p><h1>Tiến độ của tôi</h1><p>Nhìn lại những gì đã học và chọn việc tiếp theo phù hợp với bạn.</p><small>Ngày học {studyDateLabel(data.today)} · Giờ Việt Nam (UTC+7)</small></header>
    <section className="progress-streak" aria-label="Chuỗi ngày học"><div><p>Chuỗi hiện tại</p><strong>{streak.current}<span> ngày</span></strong><p>{streak.studiedToday ? 'Bạn đã ghi nhận một ngày học hôm nay.' : streak.current > 0 ? 'Học hôm nay để tiếp nối chuỗi ngày của bạn.' : 'Bắt đầu một hoạt động để tạo chuỗi ngày học mới.'}</p></div><dl><div><dt>Chuỗi dài nhất</dt><dd>{streak.longest} ngày</dd></div><div><dt>Tổng ngày đã học</dt><dd>{streak.activeDays} ngày</dd></div></dl></section>
    <section className="progress-next"><div><p className="study-eyebrow">VIỆC TIẾP THEO</p><h2>{data.nextAction.label}</h2><p>{data.nextAction.description}</p></div><Link className="study-primary" to={data.nextAction.path}>Bắt đầu →</Link></section>
    <section className="progress-today"><h2>Hôm nay bạn đã làm gì?</h2><p>{todayActivity.totalActivities === 0 ? 'Chưa có hoạt động được ghi nhận hôm nay.' : `${todayActivity.totalActivities} hoạt động đã lưu · tính một ngày học`}</p><ul><li><strong>{todayActivity.completedLessons}</strong> bài hoàn thành</li><li><strong>{todayActivity.flashcardReviews}</strong> lượt ôn thẻ</li><li><strong>{todayActivity.submittedQuizzes}</strong> Quiz đã nộp</li><li><strong>{todayActivity.totalActivities - todayActivity.completedLessons - todayActivity.flashcardReviews - todayActivity.submittedQuizzes}</strong> lượt luyện kỹ năng</li></ul></section>
    <div className="progress-metrics"><article><span>Bài đã hoàn thành</span><strong>{totals.completedLessons}<small> / {data.totalLessons}</small></strong><Link to="/learning">Bài và ghi chú của tôi →</Link></article><article><span>Lượt ôn Flashcard</span><strong>{totals.flashcardReviews}</strong><p>{data.flashcards.due} thẻ đến hạn · {data.flashcards.saved} thẻ đang lưu</p><Link to="/flashcards">Mở bộ thẻ →</Link></article><article><span>Quiz đã nộp</span><strong>{totals.submittedQuizzes}</strong><p>{totals.averageQuizScore === null ? 'Chưa có điểm Quiz' : `Trung bình ${totals.averageQuizScore.toLocaleString('vi-VN')}/100 điểm mỗi lượt`}</p><Link to="/quizzes/history">Xem kết quả →</Link></article></div>
    <section className="progress-calendar"><h2>28 ngày gần đây</h2><p>Mỗi ô là một ngày học theo giờ Việt Nam. Chọn ngày để xem hoạt động.</p><div className="progress-days">{data.calendar.map(day => <Link key={day.date} to={'/progress/history?date=' + day.date} data-active={day.totalActivities > 0} aria-current={day.date === data.today ? 'date' : undefined} aria-label={`${day.date}: ${day.totalActivities} hoạt động, ${day.completedLessons} bài, ${day.flashcardReviews} lượt ôn, ${day.submittedQuizzes} Quiz`}><span>{studyDateLabel(day.date)}</span><strong>{day.totalActivities > 0 ? day.totalActivities : '—'}</strong></Link>)}</div><p className="study-hint">Ô màu xanh nhạt: có hoạt động · Ô trắng: chưa có hoạt động. Số trong ô là lượt hoạt động, không phải điểm thành thạo.</p></section>
    <section className="progress-recent"><div className="progress-section-title"><h2>Hoạt động gần đây</h2><Link to="/progress/history">Xem tất cả →</Link></div>{data.recentActivities.length ? <ActivityList items={data.recentActivities} timeZone={data.timeZone} /> : <p className="study-empty">Chưa có lịch sử. Hoàn thành một bài, ôn một thẻ hoặc nộp một Quiz để bắt đầu.</p>}</section>
    <aside className="progress-rules"><h2>Cách tính ngày học</h2><p>Mỗi ngày có ít nhất một bài hoàn thành lần đầu, một câu trả lời Flashcard hoặc một Quiz hoặc bài luyện kỹ năng, bài nhập môn Pinyin đã nộp sẽ được tính là ngày học. Nhiều hoạt động trong ngày vẫn chỉ tính một ngày; mở trang, lưu từ hoặc làm Quiz chưa nộp không tăng chuỗi.</p><p>Ngày mới bắt đầu lúc 00:00 giờ Việt Nam. Nếu hôm qua có học, chuỗi vẫn được giữ trong hôm nay để bạn học tiếp; bỏ trọn một ngày sẽ ngắt chuỗi. Đọc lại hoặc đánh dấu lại bài đã hoàn thành không tạo thêm ngày học.</p><p>Hoàn thành bài và tự chọn “Nhớ” là ghi nhận hoạt động, chưa phải đánh giá thành thạo. Múi giờ học hiện cố định là {data.timeZone}.</p></aside>
  </>
}
