import { useState } from 'react'
import { useResource } from '../../../shared/hooks/useResource'
interface Learner { id: string; displayName: string; email: string; lastStudiedAt: string | null; foundations: number; lessons: number; activities: number }
interface Detail { activities: { id: number; label: string; score: number | null; occurredAt: string }[]; activityCount: number; foundations: { slug: string; title: string; best_score: number | null; last_score: number | null; attempts: number }[]; lessons: { title: string; completed_at: string | null }[]; review: { label: string; score: number; occurred_at: string }[] }
export function AdminLearnerProgressPage() {
  const [q,setQ] = useState(''), [days,setDays] = useState('0'), [page,setPage] = useState(0), [selected,setSelected] = useState<Learner | null>(null)
  const list = useResource<{ items: Learner[]; total: number }>(`/admin/learner-progress?${new URLSearchParams({ q, inactiveDays: days, page: String(page) })}`)
  const detail = useResource<Detail>(selected ? `/admin/learner-progress/${selected.id}` : null)
  return <main className="admin-page"><h1>Tiến độ học viên</h1><p>Theo dõi bài đã học và hoạt động gần đây. Gợi ý ôn tập dựa trên lượt làm dưới 70 điểm, không phải đánh giá năng lực.</p>
    <label>Tìm học viên<input value={q} maxLength={100} onChange={e => { setQ(e.target.value);setPage(0) }} /></label><label>Chưa học gần đây<select value={days} onChange={e => { setDays(e.target.value);setPage(0) }}><option value="0">Tất cả</option><option value="7">Ít nhất 7 ngày hoặc chưa học</option><option value="14">Ít nhất 14 ngày hoặc chưa học</option><option value="30">Ít nhất 30 ngày hoặc chưa học</option></select></label>
    {list.loading && <p role="status">Đang tải…</p>}{list.error && <p role="alert">{list.error}<button onClick={list.reload}>Thử lại</button></p>}
    {list.data && <><p>{list.data.total} học viên</p><ul>{list.data.items.map(s => <li key={s.id}><h2>{s.displayName}</h2><p>{s.email} · {s.foundations} bài nhập môn · {s.lessons} bài chủ đề · {s.activities} hoạt động</p><p>{s.lastStudiedAt ? `Học gần nhất: ${new Date(s.lastStudiedAt).toLocaleString('vi-VN')}` : 'Chưa ghi nhận hoạt động học'}</p><button onClick={() => setSelected(s)}>Xem tiến độ {s.displayName}</button></li>)}</ul><button disabled={page===0} onClick={() => setPage(page-1)}>Trang trước</button> <span>Trang {page+1}</span> <button disabled={(page+1)*20>=list.data.total} onClick={() => setPage(page+1)}>Trang sau</button></>}
    {selected && <section><h2>Chi tiết: {selected.displayName}</h2><button onClick={() => setSelected(null)}>Đóng chi tiết</button>{detail.loading && <p>Đang tải chi tiết…</p>}{detail.error && <p role="alert">{detail.error}<button onClick={detail.reload}>Thử lại</button></p>}{detail.data && <><h3>Nhập môn Pinyin</h3><ul>{detail.data.foundations.map(f => <li key={f.slug}>{f.title} · {f.attempts} lượt · tốt nhất {f.best_score ?? '—'}/100 · gần nhất {f.last_score ?? '—'}/100</li>)}</ul><h3>Bài chủ đề</h3><ul>{detail.data.lessons.map((l,i) => <li key={i}>{l.title} — {l.completed_at ? 'Đã hoàn thành' : 'Đang học'}</li>)}</ul><h3>Nên ôn lại</h3>{!detail.data.review.length && <p>Chưa có lượt dưới 70 điểm.</p>}<ul>{detail.data.review.map((r,i) => <li key={i}>{r.label} · {r.score}/100 · {new Date(r.occurred_at).toLocaleDateString('vi-VN')}</li>)}</ul><h3>50 hoạt động gần nhất / tổng {detail.data.activityCount}</h3><ol>{detail.data.activities.map(a => <li key={a.id}>{a.label} {a.score!==null && `· ${a.score}/100`} · {new Date(a.occurredAt).toLocaleString('vi-VN')}</li>)}</ol></>}</section>}
  </main>
}
